// Auto-generated by typescript_record_browser_flow from @playwright/mcp tool calls.
// Flow: dashboard-load
// Dev server: http://localhost:1420
import { test, expect } from '@playwright/test';

test('dashboard-load', async ({ page }) => {
  await page.goto('http://localhost:1420');
  // Press Escape
  await page.keyboard.press('Escape');
  // Screenshot viewport and save it as .playwright-mcp\page-2026-06-26T10-26-10-008Z.png
  await page.screenshot({
    path: '.playwright-mcp\\page-2026-06-26T10-26-10-008Z.png',
    scale: 'css',
    type: 'png'
  });
  // Screenshot viewport and save it as .playwright-mcp\page-2026-06-26T10-26-10-219Z.png
  await page.screenshot({
    path: '.playwright-mcp\\page-2026-06-26T10-26-10-219Z.png',
    scale: 'css',
    type: 'png'
  });
  // Screenshot viewport and save it as .playwright-mcp\page-2026-06-26T10-26-10-505Z.png
  await page.screenshot({
    path: '.playwright-mcp\\page-2026-06-26T10-26-10-505Z.png',
    scale: 'css',
    type: 'png'
  });
});
